name: alethic-ism-processor-openai
channels:
  - file:///app/conda/env/local_channel
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - psycopg2
  - pyyaml
  - pydantic
  - pydantic-core
  - pulsar-client
  - openai
  - tenacity
  - restrictedpython
  - alethic-ism-core
  - alethic-ism-db
