apiVersion: v1
kind: Secret
metadata:
  name: alethic-ism-processor-openai-secret
  namespace: alethic
stringData:
#  ROUTING_FILE: "/app/config/routing.yaml/routing.yaml"
  LOG_LEVEL: "INFO"
  DATABASE_URL: "postgresql://<<db_user>>:<<db_pass>>@alethic-db-service:5432/ism_db"
  OPENAI_API_KEY: "<<primary openai key>>"
  MSG_URL: "pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650"
  MSG_TOPIC: "ism_openai_qa"
  MSG_MANAGE_TOPIC: "ism_openai_qa_manage"
  MSG_TOPIC_SUBSCRIPTION: "ism_openai_qa_subscription"
  .routing.yaml: |
    messageConfig:
        root_route:
          topic: ism_general
          manage_topic: ism_general_manage
          subscription: ism_general_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

        topic_routes:
        - selector: processor/monitor
          topic: ism_monitor
          manage_topic: ism_monitor_monitor
          subscription: ism_monitor_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650

        - selector: state/sync/store
          topic: ism_state_sync_store
          subscription: ism_state_sync_store_subscription
          service_url: pulsar://pulsar-proxy.pulsar.svc.cluster.local:6650
